// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: express/express_service.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Grpc.Business.ExpressService {
  public static partial class ExpessService
  {
    static readonly string __ServiceName = "express.ExpessService";

    static readonly grpc::Marshaller<global::Grpc.Business.ExpressService.DocId> __Marshaller_DocId = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Business.ExpressService.DocId.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Grpc.Business.ExpressService.ActiveData> __Marshaller_ActiveData = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Grpc.Business.ExpressService.ActiveData.Parser.ParseFrom);

    static readonly grpc::Method<global::Grpc.Business.ExpressService.DocId, global::Grpc.Business.ExpressService.ActiveData> __Method_GetActive = new grpc::Method<global::Grpc.Business.ExpressService.DocId, global::Grpc.Business.ExpressService.ActiveData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetActive",
        __Marshaller_DocId,
        __Marshaller_ActiveData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Grpc.Business.ExpressService.ExpressServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ExpessService</summary>
    public abstract partial class ExpessServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Grpc.Business.ExpressService.ActiveData> GetActive(global::Grpc.Business.ExpressService.DocId request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ExpessService</summary>
    public partial class ExpessServiceClient : grpc::ClientBase<ExpessServiceClient>
    {
      /// <summary>Creates a new client for ExpessService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ExpessServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ExpessService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ExpessServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ExpessServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ExpessServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Grpc.Business.ExpressService.ActiveData GetActive(global::Grpc.Business.ExpressService.DocId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetActive(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Grpc.Business.ExpressService.ActiveData GetActive(global::Grpc.Business.ExpressService.DocId request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetActive, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Business.ExpressService.ActiveData> GetActiveAsync(global::Grpc.Business.ExpressService.DocId request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetActiveAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Grpc.Business.ExpressService.ActiveData> GetActiveAsync(global::Grpc.Business.ExpressService.DocId request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetActive, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ExpessServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ExpessServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ExpessServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetActive, serviceImpl.GetActive).Build();
    }

  }
}
#endregion
